apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectorschema.yaml
  - microedgeconfiguration.yaml
  - generictopologyprocessor-deployment.yaml
  - generictopologyprocessor-service.yaml
  - generictopologyprocessor-serviceaccount.yaml
  - generictopologyprocessor-observerrole.yaml
  - generictopologyprocessor-observerrolebinding.yaml
  - topics.yaml

configurations:
  - custom-images.yaml

images:
  - name: java-grpc-connector-template
    newName: docker.io/rolivieri/java-grpc-connector-template
    newTag: latest
  - name: generic-topology-processor
    newName: cp.icr.io/cp/cp4waiops/generic-topology-processor
    digest: sha256:4caa17dd869ee30e95a1c222c9faafe6e3ed2b3f22183c7296f02ffdf6cacad8